In [1]:
import numpy as np
import pandas as pd

In [2]:
inp_train=input('Please enter the name of the train data file (e.g. pid.dat): ')
inp_test=input('Please enter the name of the test data file (e.g. pidtest.dat): ')
encode_sep=int(input("Please select the separator used in the data file (1 = whitespace or 2 = comma): "))
separator={encode_sep ==1 : " "}.get(True, ",")
res_pos =int(input("Please enter the position of the response variable column (select from 1 to p) (e.g. 8): "))
header=input("Does the data file include a column header? (y/n) : ")
export_name=input("Please enter the name for the file to be exported (e.g. result.txt) : ")

Please enter the name of the train data file (e.g. pid.dat): pid.dat
Please enter the name of the test data file (e.g. pidtest.dat): pidtest.dat
Please select the separator used in the data file (1 = whitespace or 2 = comma): 2
Please enter the position of the response variable column (select from 1 to p) (e.g. 8): 8
Does the data file include a column header? (y/n) : n
Please enter the name for the file to be exported (e.g. result.txt) : HW6_output.txt


In [3]:
if(header=='y'):
    train = pd.read_csv(inp_train, sep=separator)
    test = pd.read_csv(inp_test, sep=separator)
else:
    train = pd.read_csv(inp_train, sep=separator, header = None)
    test = pd.read_csv(inp_test, sep=separator, header = None)  

In [4]:
x_train=train.iloc[:,:res_pos-1]
x_train

0    1    2   3     4      5   6
0     4   83   86  19  29.3  0.317  34
1     6  105   70  32  30.8  0.122  37
2     1   89   24  19  27.8  0.559  21
3     6  111   64  39  34.2  0.260  24
4     4  146   85  27  28.9  0.189  27
..   ..  ...  ...  ..   ...    ...  ..
247   2   68   62  13  20.1  0.257  23
248  10   68  106  23  35.5  0.285  47
249   3   99   80  11  19.3  0.284  30
250   1  124   74  36  27.8  0.100  30
251   6  123   72  45  33.6  0.733  34

[252 rows x 7 columns]

In [5]:
y_train=train.iloc[:,res_pos-1]
y_train

0      2
1      2
2      2
3      2
4      2
      ..
247    2
248    2
249    2
250    2
251    2
Name: 7, Length: 252, dtype: int64

In [6]:
x_test=test.iloc[:,:res_pos-1]
x_test

0    1    2   3     4      5   6
0     5  136   84  41  35.0  0.286  35
1     9  170   74  31  44.0  0.403  43
2    14  175   62  30  33.6  0.212  38
3     7  160   54  32  30.5  0.588  39
4     0  180   90  26  36.5  0.314  35
..   ..  ...  ...  ..   ...    ...  ..
221   8  105  100  36  43.3  0.239  45
222  11  143   94  33  36.6  0.254  51
223   1  168   88  29  35.0  0.905  52
224   1  122   64  32  35.1  0.692  30
225   1  181   64  30  34.1  0.328  38

[226 rows x 7 columns]

In [7]:
y_test=test.iloc[:,res_pos-1]
y_test

0      1
1      1
2      1
3      1
4      1
      ..
221    1
222    1
223    1
224    1
225    1
Name: 7, Length: 226, dtype: int64

### GINI Impurity

In [8]:
response=np.unique(y_train)

In [9]:
def GINI_impurity(data):
    n=len(data)
    p1 = sum(data == response[0])/n
    p2 = sum(data == response[1])/n
    gini = 1 - (p1**2+p2**2)
    
    return gini

In [10]:
gini_train = GINI_impurity(y_train)
np.round(gini_train,4)

0.4082

In [11]:
gini_test = GINI_impurity(y_test)
np.round(gini_test,4)

0.4735

### Greedy Search Algorithm

In [12]:
max_goodness = [] #Store best goodness of split values
max_index = [] #Store indices for goodness of split

In [13]:
np.unique(x_train[1])

array([ 68,  71,  72,  73,  74,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
        98,  99, 100, 101, 102, 103, 105, 106, 107, 108, 109, 110, 111,
       112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
       125, 126, 127, 128, 129, 130, 131, 135, 137, 138, 139, 140, 142,
       143, 144, 145, 146, 147, 148, 149, 151, 152, 153, 154, 155, 156,
       157, 158, 164, 165, 166, 167, 173, 174, 176, 179, 180, 181, 184,
       187, 188, 189, 191, 193, 194, 195, 196, 197, 198], dtype=int64)

In [14]:
x_train

0    1    2   3     4      5   6
0     4   83   86  19  29.3  0.317  34
1     6  105   70  32  30.8  0.122  37
2     1   89   24  19  27.8  0.559  21
3     6  111   64  39  34.2  0.260  24
4     4  146   85  27  28.9  0.189  27
..   ..  ...  ...  ..   ...    ...  ..
247   2   68   62  13  20.1  0.257  23
248  10   68  106  23  35.5  0.285  47
249   3   99   80  11  19.3  0.284  30
250   1  124   74  36  27.8  0.100  30
251   6  123   72  45  33.6  0.733  34

[252 rows x 7 columns]

In [15]:
x_train

0    1    2   3     4      5   6
0     4   83   86  19  29.3  0.317  34
1     6  105   70  32  30.8  0.122  37
2     1   89   24  19  27.8  0.559  21
3     6  111   64  39  34.2  0.260  24
4     4  146   85  27  28.9  0.189  27
..   ..  ...  ...  ..   ...    ...  ..
247   2   68   62  13  20.1  0.257  23
248  10   68  106  23  35.5  0.285  47
249   3   99   80  11  19.3  0.284  30
250   1  124   74  36  27.8  0.100  30
251   6  123   72  45  33.6  0.733  34

[252 rows x 7 columns]

In [16]:
for i in range(len(x_train.T)):
    xmeans = [] #List for storing splitting points
    for j in range(len(np.unique(x_train[i]))-1):
        xmeans.append((np.unique(x_train[i])[j] + np.unique(x_train[i])[j+1])/2) #Calculate splitting points
        
    #Calculate goodness of split
    goodness = [] #Store goodness of split values
    for k in range(len(xmeans)):
        #apply split rule
        left = x_train[i] <= xmeans[k]
        right = x_train[i] > xmeans[k]

        #weights for GINI impurity
        w1 = sum(left)/len(x_train)
        w2 = sum(right)/len(x_train)

        splits=GINI_impurity(y_train) - (w1*GINI_impurity(y_train[left]) + w2*GINI_impurity(y_train[right]))
        goodness.append(splits)

    #Save values
    max_goodness.append(max(goodness))
    max_index.append(np.argmax(goodness))

    #Finding variable with best goodness of split
    variable = str(np.argmax(max_goodness)+1)
    
    #Coressponding split point
    split_point = (np.unique(x_train[np.argmax(max_goodness)])[max_index[np.argmax(max_goodness)]] + np.unique(x_train[np.argmax(max_goodness)])[max_index[np.argmax(max_goodness)]+1])/2

In [17]:
#Splitting points
xmeans

[21.5,
 22.5,
 23.5,
 24.5,
 25.5,
 26.5,
 27.5,
 28.5,
 29.5,
 30.5,
 31.5,
 32.5,
 33.5,
 34.5,
 35.5,
 36.5,
 37.5,
 38.5,
 39.5,
 40.5,
 41.5,
 42.5,
 44.0,
 45.5,
 46.5,
 47.5,
 48.5,
 49.5,
 50.5,
 51.5,
 53.5,
 55.5,
 56.5,
 57.5,
 58.5,
 59.5,
 61.0,
 62.5]

In [18]:
#Best goodness of split values
np.round(max_goodness,4)

array([0.055 , 0.0953, 0.0137, 0.022 , 0.026 , 0.0337, 0.0471])

In [19]:
#Corresponding indices of observations
max_index

[6, 68, 19, 11, 46, 151, 7]

In [20]:
#Splitting variable
variable

'2'

In [21]:
#Final splitting point
split_point

146.5

### Confusion Matrix and Accuracy

In [22]:
#Fit predictor variables of test data into model
pred=np.where(x_test[int(variable)-1]<=split_point,2,1)
pred

array([2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 2,
       1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1,
       1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2,
       1, 2, 2, 1, 2, 1])

In [23]:
#Response variables of test data
y_test=np.array(y_test)
y_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [24]:
#Confusion matrix
confusion=pd.crosstab(y_test, pred, colnames=[''])
confusion.index = np.array(['Actual', 'Class'])
confusion.insert(loc=0, value=np.unique(pred), column = '')

In [25]:
print("Confusion Matrix (Test)\n", "-----------------------\n", "      Predicted Class\n", confusion)

Confusion Matrix (Test)
 -----------------------
       Predicted Class
             1    2
Actual  1  37   50
Class   2  11  128


In [26]:
#Accuracy
acc_test = np.round(np.trace(pd.crosstab(y_test, pred))/len(test),3)
acc_test

0.73

### Write File

In [27]:
f = open(export_name,'w')
text=""
text+="Tree Structure\n      Node 1: "+str(response[1])+" ("+str(sum(y_train == response[0]))+", "+str(sum(y_train == response[1]))
text+=")\n          Node 2: x"+str(variable)+" <= "+str(split_point)+", "+str(response[1])+" ("
text+=str(sum(y_train[x_train[1] <= split_point] == response[0]))+", "+str(sum(y_train[x_train[1] <= split_point] == response[1]))
text+=")\n          Node 3: x"+str(variable)+" > "+str(split_point)+", "+str(response[0])+" ("
text+=str(sum(y_train[x_train[1] > split_point] == response[0]))+", "+str(sum(y_train[x_train[1] > split_point] == response[1]))+")"

text+="\n\nConfusion Matrix (Test)\n"+"-------------------------------\n"+"      Predicted Class\n"+str(confusion)

text += "\n\nModel Summary (Test)\n-----------------------------\n"
text += "Overall accuracy = "+str(acc_test)+"\n\n\n"

f.write(text)
f.close()